export class GenericUtils {
  static PORTFOLIO_LIST = 'PORTFOLIO_LIST';
  static PORTFOLIO_STATS = 'PORTFOLIO_STATS';
  static PORTFOLIO_TRADES = 'PORTFOLIO_TRADES';
  static LAST_UPDATE = 'LAST_UPDATE';
}
